# Generated by Django 5.2.6 on 2025-09-20 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "generic_name",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "form",
                    models.CharField(
                        choices=[
                            ("Tablet", "Tablet"),
                            ("Capsule", "Capsule"),
                            ("Syrup", "Syrup"),
                            ("Injection", "Injection"),
                        ],
                        max_length=45,
                    ),
                ),
                ("strength", models.CharField(max_length=45)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("IN", "In Stock"), ("OUT", "Out of Stock")],
                        default="IN",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicine_app.medicine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pharmacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                ("city", models.CharField(max_length=45)),
                ("address", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=45)),
                ("is_active", models.BooleanField(default=True)),
                ("cr_number", models.CharField(max_length=30, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "medicines",
                    models.ManyToManyField(
                        related_name="pharmacies",
                        through="medicine_app.Inventory",
                        to="medicine_app.medicine",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacies",
                        to="medicine_app.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "name", "city")},
            },
        ),
        migrations.AddField(
            model_name="inventory",
            name="pharmacy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="medicine_app.pharmacy"
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medicines",
                to="medicine_app.user",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventory",
            unique_together={("medicine", "pharmacy")},
        ),
        migrations.AlterUniqueTogether(
            name="medicine",
            unique_together={("created_by", "name", "strength", "form")},
        ),
    ]
