# Generated by Django 5.2.6 on 2025-09-20 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicine_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="medicine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="medicine_app.medicine",
            ),
        ),
    ]
