# Generated by Django 5.2.6 on 2025-09-22 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicine_app", "0002_alter_inventory_medicine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="pharmacy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="medicine_app.pharmacy",
            ),
        ),
    ]
